### ISSUE TITLE
Radio buttons not saving state

### ISSUE THREAD

**Issue by t1mduma5** [wphuman/WordPress-Settings-Module#4]
The radio buttons are only half saving state. If I check "Yes" it saves and when you revisit the tab the "Yes" radio button is checked. If I select "No" it _saves_ and reloads as unchecked. If I leave and come back nothing is checked. I do have text fields on other tabs that are saving their state perfectly. 

Any idea what would cause that?

Here is the definition array
`$settings['general_tab']['mpact_spamstamp_inline_style'] = array(`
`'name'    => __( 'Inline Style', self::$plugin_name ),`
`'desc'    => __( 'If you are comfortable editing your site\'s stylesheet you can place the styles there rather than inline.', self::$plugin_name ),`
`'options' => array(`
`'1' => __( "Yes - Place the form elements style inline", self::$plugin_name ),`
`'0'  => __( "No - I want to place the form elements style in CSS.", self::$plugin_name ),`
`),`
`'type'    => 'radio'`
`);`

**Comment by t1mduma5** [comment]
It's the '0' that is causing it to not save state on the radio button.

I tried it with [true|false], [Y|N], [Yes|No], etc and it worked every time. Just can't use [1|0].

Is that by design, necessity or it is a bug, an oversight?

Thanks

**Comment by tangrufus** [comment]
By design, I try not saving any empty or '0' values into the database 

The Plugin_Name_Sanitization_Helper class is responsible for this. 
Take a look at at the 'private function get_output'

If saving '0' is important to your plugin, you might want to modify the Plugin_Name_Sanitization_Helper class.
