### ISSUE TITLE
"Not Working" Installation guide.

### ISSUE THREAD

**Issue by denisstoyanov** [wphuman/WordPress-Settings-Module#5]
Hi,

Have you removed https://wphuman.com/announcing-wordpress-settings-module/, because it's no longer opening on my end. I am currently reading the Google Cached page. Thank you for the feedback :)

**Comment by tangrufus** [comment]
making some change on wp human server. 
For the time being, go to [www.wphuman.com](https://www.wphuman.com/announcing-wordpress-settings-module/) instead.
