### ISSUE TITLE
Question: Add additional options that are updated during post save

### ISSUE THREAD

**Issue by sixtyseven-multimedia** [wphuman/WordPress-Settings-Module#7]
Hi from germany,

first of all: Kudos for your work. Your Settings module makes a perfect addtion to the WPPB. Easy to use, even for a beginner like me. And easily extendable with for example a color option field.

I need a little help with a special case, though:
I want to add options, that are not maintained on the settings tabs. In my case, I want to store an option during the saving of a post (here: the id of this post, if it uses a certain shortcode), that will work out fine during the save_post hook. What I now want to achieve, ist to put this option into the array of options that is saved by the metabox, so that a) I have it in the same database query and b) could handle it with your nice static get_option function.

I hope I could explain my problem well enough. Could you probably help me with that? I am quite clueless how to do this. Thank you in advance.

**Comment by tangrufus** [comment]
You are looking for `post metaboxes`. 
Take a look at this [tutorial](http://themefoundation.com/wordpress-meta-boxes-guide/)

Although  `post metaboxes` are out of the scope of this module, you can make use of `Plugin_Name_Callback_Helper` and `Plugin_Name_Sanitization_Helper` to generate your `post metaboxes`.

Note: Not to confuse with the class `Plugin_Name_Meta_Box`.
