### ISSUE TITLE
Undefined property: Plugin_Name_Meta_Box::$snake_cased_plugin_name

### ISSUE THREAD

**Issue by digitalchild** [wphuman/WordPress-Settings-Module#8]
https://github.com/wphuman/WordPress-Settings-Module/blob/master/admin/partials/plugin-name-meta-box-display.php#L22-L23

I think these lines are supposed to be updated to plugin_name as per 7befb8971dfb693e877063cd9fa46f0b9de00ac9

**Comment by tangrufus** [comment]
I missed some files when replacing `$snake_cased_plugin_name` with hard-coded `plugin_name` stings.
Fixed in b5b7f2d3b9bcaacbbe383c4632636c83e59c591c
Thx
